app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
  auth:
    oauth-success:
      frontend-redirect-uri: ${OAUTH_SUCCESS_FRONTEND_REDIRECT_URI}
    token:
      secret: ${JWT_SECRET}
    refresh-token-cookie:
      secure: ${REFRESH_TOKEN_COOKIE_SECURE:true}
      same-site: ${REFRESH_TOKEN_COOKIE_SAME_SITE:Lax}
