package com.studywithme.notification.domain;

public enum NotificationType {
	COMMENT_ON_POST,
	REPLY_ON_COMMENT,
	MENTIONED_IN_COMMENT,
	STUDY_JOIN_REQUESTED,
	STUDY_JOIN_APPROVED,
	STUDY_JOIN_REJECTED,
	STUDY_JOIN_CANCELLED,
	STUDY_ENDED,
	STUDY_DELETED
}
