create table chat_message_reports (
    id bigint generated by default as identity,
    room_id bigint not null,
    message_id bigint not null,
    reporter_member_id bigint not null,
    reported_member_id bigint not null,
    reason varchar(500) not null,
    status varchar(20) not null,
    handler_member_id bigint,
    handling_note varchar(500),
    created_at timestamp not null,
    handled_at timestamp,
    primary key (id),
    constraint fk_chat_message_reports_room foreign key (room_id) references chat_rooms (id),
    constraint fk_chat_message_reports_message foreign key (message_id) references chat_messages (id),
    constraint fk_chat_message_reports_reporter foreign key (reporter_member_id) references members (id),
    constraint fk_chat_message_reports_reported foreign key (reported_member_id) references members (id),
    constraint fk_chat_message_reports_handler foreign key (handler_member_id) references members (id),
    constraint uk_chat_message_reports_message_reporter unique (message_id, reporter_member_id)
);

create index idx_chat_message_reports_status_created
    on chat_message_reports (status, created_at desc, id desc);
