create table members (
    id bigint generated by default as identity,
    email varchar(255) not null,
    nickname varchar(50) not null,
    oauth_provider varchar(20) not null,
    oauth_subject varchar(100) not null,
    profile_image_url varchar(500),
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint uk_members_oauth_provider_subject unique (oauth_provider, oauth_subject),
    constraint uk_members_nickname unique (nickname)
);

create index idx_members_email on members (email);

create table member_roles (
    member_id bigint not null,
    role varchar(20) not null,
    primary key (member_id, role),
    constraint fk_member_roles_member foreign key (member_id) references members (id)
);
