create table refresh_tokens (
    id bigint generated by default as identity,
    member_id bigint not null,
    token_hash varchar(100) not null,
    issued_at timestamp not null,
    expires_at timestamp not null,
    rotated_at timestamp,
    revoked_at timestamp,
    primary key (id),
    constraint uk_refresh_tokens_token_hash unique (token_hash),
    constraint fk_refresh_tokens_member foreign key (member_id) references members (id)
);

create index idx_refresh_tokens_member_id on refresh_tokens (member_id);
create index idx_refresh_tokens_expires_at on refresh_tokens (expires_at);
