create table studies (
    id bigint generated by default as identity,
    owner_member_id bigint not null,
    title varchar(100) not null,
    description varchar(2000) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint fk_studies_owner_member foreign key (owner_member_id) references members (id)
);

create index idx_studies_status_created_at on studies (status, created_at desc);
create index idx_studies_owner_member_id on studies (owner_member_id);

create table study_members (
    id bigint generated by default as identity,
    study_id bigint not null,
    member_id bigint not null,
    role varchar(20) not null,
    joined_at timestamp not null,
    primary key (id),
    constraint fk_study_members_study foreign key (study_id) references studies (id),
    constraint fk_study_members_member foreign key (member_id) references members (id),
    constraint uk_study_members_study_member unique (study_id, member_id)
);

create index idx_study_members_member_id on study_members (member_id);
