create table posts (
    id bigint generated by default as identity,
    author_member_id bigint not null,
    title varchar(100) not null,
    content varchar(5000) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint fk_posts_author_member foreign key (author_member_id) references members (id)
);

create index idx_posts_status_created_at on posts (status, created_at desc);
create index idx_posts_author_member_id on posts (author_member_id);
