create table comments (
    id bigint generated by default as identity,
    post_id bigint not null,
    author_member_id bigint not null,
    parent_comment_id bigint,
    content varchar(1000) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint fk_comments_post foreign key (post_id) references posts (id),
    constraint fk_comments_author_member foreign key (author_member_id) references members (id),
    constraint fk_comments_parent_comment foreign key (parent_comment_id) references comments (id)
);

create index idx_comments_post_status_created_at on comments (post_id, status, created_at asc);
create index idx_comments_parent_comment_id on comments (parent_comment_id);
create index idx_comments_author_member_id on comments (author_member_id);
