create table outbox_events (
    id varchar(36) not null,
    event_type varchar(50) not null,
    aggregate_type varchar(50) not null,
    aggregate_id bigint not null,
    payload text not null,
    status varchar(20) not null,
    retry_count integer not null,
    next_attempt_at timestamp not null,
    occurred_at timestamp not null,
    processed_at timestamp,
    last_error varchar(1000),
    primary key (id)
);

create index idx_outbox_events_status_next_attempt_at
    on outbox_events (status, next_attempt_at, occurred_at);

create table notifications (
    id bigint generated by default as identity,
    receiver_member_id bigint not null,
    actor_member_id bigint not null,
    type varchar(50) not null,
    target_type varchar(50) not null,
    target_id bigint not null,
    source_event_id varchar(36) not null,
    message varchar(500) not null,
    read_at timestamp,
    created_at timestamp not null,
    primary key (id),
    constraint fk_notifications_receiver_member foreign key (receiver_member_id) references members (id),
    constraint fk_notifications_actor_member foreign key (actor_member_id) references members (id),
    constraint uk_notifications_source_receiver_type unique (source_event_id, receiver_member_id, type)
);

create index idx_notifications_receiver_created_at
    on notifications (receiver_member_id, created_at desc);
