create table chat_rooms (
    id bigint generated by default as identity,
    type varchar(20) not null,
    room_key varchar(100) not null,
    study_id bigint,
    created_at timestamp not null,
    primary key (id),
    constraint uk_chat_rooms_room_key unique (room_key),
    constraint fk_chat_rooms_study foreign key (study_id) references studies (id)
);

create index idx_chat_rooms_study_id on chat_rooms (study_id);

create table chat_room_members (
    id bigint generated by default as identity,
    room_id bigint not null,
    member_id bigint not null,
    joined_at timestamp not null,
    primary key (id),
    constraint fk_chat_room_members_room foreign key (room_id) references chat_rooms (id),
    constraint fk_chat_room_members_member foreign key (member_id) references members (id),
    constraint uk_chat_room_members_room_member unique (room_id, member_id)
);

create index idx_chat_room_members_member_joined_at
    on chat_room_members (member_id, joined_at desc);

create table chat_messages (
    id bigint generated by default as identity,
    room_id bigint not null,
    sender_member_id bigint not null,
    content varchar(1000) not null,
    created_at timestamp not null,
    primary key (id),
    constraint fk_chat_messages_room foreign key (room_id) references chat_rooms (id),
    constraint fk_chat_messages_sender_member foreign key (sender_member_id) references members (id)
);

create index idx_chat_messages_room_created_id
    on chat_messages (room_id, created_at, id);
